stages:
    - build
    - test
    - deploy
    - sonar

image: gradle:6.8.3-jdk15
before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle

variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
    stage: build
    script:
        - gradle --build-cache assemble
    cache:
        key: $CI_COMMIT_REF_NAME
        policy: push
        paths:
            - build
            - .gradle

staging:
    stage: deploy
    image: ruby:2.7.3-buster
    before_script:
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_NAME_DEV --api-key=$HEROKU_API_KEY
    cache: {}
    only:
        - dev

production:
    stage: deploy
    image: ruby:2.7.3-buster
    before_script:
        - gem install dpl
    script:
        - dpl --provider=heroku --app=$HEROKU_APPNAME_PROD --api-key=$HEROKU_API_KEY
    cache: {}
    only:
        - master

sonarCheck:
    stage: sonar
    needs:
        - job: test
    script:
        - gradle sonarqube -Dsonar.login=$SONAR_TOKEN

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - $GRADLE_USER_HOME/wrapper
        - $GRADLE_USER_HOME/caches
